INSERT INTO users (userid, firstname, lastname, roll, email) VALUES 
('mjquinn','Michael','Quinn','56','mjquinn@umich.edu'),
('reedml','Maggie','(Reed) Myers','83','reedml@umich.edu'),
('kgunberg','Kate','Gunberg','53','kate.gunberg@gmail.com'),
('pconlin','Paul','Conlin','49','pconlin@umich.edu'),
('gregfi','Greg','Fischer','60','Greg.A.Fischer@gmail.com'),
('patelmn','Monika','Patel','69','patelmn@umich.edu'),
('jfairchi','Joe','Fairchild','58','jfairchi@umich.edu'),
('darrint','Darrin','Tracy','39','darrin.tracy@gmail.com'),
('dbzero','Dan','Jensen','2','dbzero@umich.edu'),
('ensignlm','Larisa','Ensign','81','ensignlm@umich.edu'),
('rauchs','Suzanne','Rauch','45','smrauch@gmail.com'),
('squintan','Sara','Quintana','47','squintan@gmail.edu'),
('jjwashbu','Justin','Washburn','48','jjwashbu@umich.edu'),
('quanz','Quan (Kevin)','Zhu','86','quanz@umich.edu'),
('rburkhar','Russell','Burkhard','51','rburkhar@umich.edu'),
('kdashair','Kiran','Dashairya','62','kdashair@gmail.com'),
('pdoll','Patrick','Doll','55','pdoll@umich.edu'),
('angraor','Amanda','Graor','57','angraor@umich.edu'),
('jlkron','Jessica','Kron','59','jlkron@umich.edu'),
('dpinkney','David','Pinkney','61','dpinkney@umich.edu'),
('emschmid','Erica','Schmidt','52','emschmid@umich.edu'),
('jcgrimm','Jeff','Grimm','63','jcgrimm@umich.edu'),
('malbrigh','Michelle','Albright','64','malbrigh@gmail.com'),
('stoloreb','Rebecca','Stoloff','65','stoloreb@umich.edu'),
('davemich','David','Preston','66','davemich@umich.edu'),
('akluck','Aaron','Kluck','67','akluck@gmail.com'),
('markalan','Mark','Thomas','68','mark.thomas.jr@gmail.com'),
('kofahlum','Philip','Kofahl','70','kofahlum@umich.edu'),
('rmsherm','Becky','Sherman','71','rmsherm@gmail.com'),
('alexkotu','Alex','Kotula','72','ahkotula@gmail.com'),
('mjbyom','Matt','Byom','73','mjbyom@umich.edu'),
('mmbowman','Matt','Bowman','74','mmbowman@umich.edu'),
('schremsa','Adam','Schrems','75','schremsa@umich.edu'),
('sbarr','Sarah','Barr','77','sbarr@umich.edu'),
('jmdonogh','Joel','Donoghue','78','jmdonogh@umich.edu'),
('dparrotb','Danielle','Boyle (White)','79','danielle.parrott@gmail.com'),
('maherk','Kate','Maher','80','maherk@umich.edu'),
('andredan','Andrew','Danielsky','132','andredan@umich.edu'),
('tketai','Theodore','Ketai','43','tketai@gmail.com'),
('milliken','Jacob','Milliken','82','jamilliken@aep.com'),
('katsb','Kathryn','Blodgett','84','katsb@gatech.edu'),
('emr','Erin','Robbins','50','robbins.erin@gmail.com'),
('cmarti','Courtney','Martin','89','cmarti@umich.edu'),
('benfried','Ben','Friedland','90','benfried@umich.edu'),
('muskr','Carl','Fischer','4','Carl.Fischer.IV@gmail.com'),
('cworthem','Cullen','Worthem Jr.','1','cworthem@umich.edu'),
('jbroggio','Julian','Broggio','3','jbroggio@hotmail.com'),
('rsekela1','Ryan','Sekela','5','rsekela1@visteon.com'),
('derekdcs','Derek','Sorensen','6','derekdcs@umich.edu'),
('rmeder','Ryan','Meder','7','rmeder@engin.umich.edu'),
('jjbailey08','Jason','Bailey','8','jjbailey08@gmail.com'),
('afurman','Aaron','Furman','9','afurman@umich.edu'),
('mfeustel','Matt','Feustel','10','mfeustel@umich.edu'),
('batchac','Drew','Batchelder','11','andrew.c.batchelder@lmco.com'),
('mascione','Mark','Ascione','12','mcascione@gmail.com'),
('aolosfsk','Angie','Olsofsky','13','aolosfsk@yahoo.com'),
('jhschaef','Julianne','Schaefer','14','jhschaef@yahoo.com'),
('david.moenssen','Dave','Moenssen','15','david.moenssen@honeywell.com'),
('todd_moilanen','Todd','Moilanen','16','todd_moilanen@hotmail.com'),
('dcepeda','Darin','Cepeda','17','decepda@austin.rr.com'),
('sbisgaie','Stan','Bisgaier','18','stanb@ufl.edu'),
('qzhxfp','Beth','(Tuttle) Gardner','20','tuttleelizabeth@hotmail.com'),
('jpmyers','John','Myers','21','jpmyers@umich.edu'),
('dwallen','Dan','Allen','22','dwallen@umich.edu'),
('philipw','Philip','Waligora','24','phil.waligora@gmail.com'),
('molsofsk','Matthew','Olsofsky','25','molsofsk@umich.edu'),
('gsabo','Gregory','Sabo','26','gsabo@umich.edu'),
('mehtat','Tanuj','Mehta','27','mehtat@hotmail.com'),
('mgiska','Mark','Giska','28','mgiska@umich.edu'),
('stepania','Jack','Stepanian','30','stepania@umich.edu'),
('avalique','Andy','Valiquett','31','avalique@umich.edu'),
('ntapia','Nityanan','Tapia','32','nityanantapia@hotmail.com'),
('jjinnah','Javed','Jinnah','35','jjinnah@umich.edu'),
('jdaunoravicius','Jonas','Daunoravicius','36','jdaunora@gmail.com'),
('lravindr','Latha','Mellentine','38','lravindr@gmail.com'),
('jrtervol','Ray','Tervol','41','jrtervol@yahoo.com'),
('cvanitt','Christopher','Van Ittersum','42','cvanitt@umich.edu'),
('mperaino','Mark','Peraino','44','mperaino@umich.edu'),
('bkilbour','Beth','Kilbourne','46','bkilbour@umich.edu'),
('jmellent','James','Mellentine','29','umichjim@gmail.com'),
('rileym','Marvin','Riley','34','mracer314@yahoo.com'),
('rbronson','Reid','Bronson','37','rbronson@umich.edu'),
('bsw','Bayly','Wheeler','40','bsw@duke.edu'),
('cdsadler','Christina','Sadler','93','cdsadler@umich.edu'),
('ebusen','Eli','Busen','95','ebusen@gmail.com'),
('fltr','Patrick','Liu','109','ltrick@umich.edu'),
('meganelb','Megan','Brown','156','meganelb@umich.edu'),
('fszalay','Francis','Szalay','98','fszalay@gmail.com'),
('furlongl','Lauren','Furlong','103','furlongl@umich.edu'),
('jamesbl','James','Bloomsburgh','91','jamesbl@umich.edu'),
('jldolan','Jennifer','Dolan','92','jldolan@umich.edu'),
('jsuther','Jennifer','Sutherland','101','jsuther@umich.edu'),
('mezen','Michelle','Zenczak','97','mezen@umich.edu'),
('hnpatel','Heetal','Patel','107','hnpatel@umich.edu'),
('kert','Kurt','Oster','108','kurt.oster@gmail.com'),
('hkast','Hillary','Kast','105','hkast@umich.edu'),
('jamesrg','James','Glantz','237','jamesrg@umich.edu'),
('mwrod','Matthew','Rodriguez','94','mwrod@umich.edu'),
('nkizy','Nicole','Kizy','100','nkizy@umich.edu'),
('sassyk','Kendra','Sass','96','sassyk@umich.edu'),
('smiatrow','Stephanie','Iatrow','102','smiatrow@umich.edu'),
('kjsand','Kelly','Sanderson','104','kjsand@umich.edu'),
('xjsixjag','Nate','LaFave','99','nathan.lafave@gmail.com'),
('freemaja','Jim','Freeman','121','freemaja@gmail.com'),
('ajfrantz','AJ','Frantz','113','ajfrantz@umich.edu'),
('clemense','Eily','Clemens','114','clemense@umich.edu'),
('jengehle','Jennifer','Gehle','110','jengehle@umich.edu'),
('mirim','Miriam','Scherkenbach','116','mirim@umich.edu'),
('weitung','Cindy','Wang','117','weitung@umich.edu'),
('grailo','Nick','McGrail','120','grailo@umich.edu'),
('vinnyv','Vincent','Verdeschi','112','vinnyv@umich.edu'),
('stanvi','Tanvi','Singh','119','stanvi@umich.edu'),
('phalexan','Phillip','Clark','118','phillip.a.clark@gmail.com'),
('kadann','Kristin','Dannemiller','157','kadann@umich.edu'),
('armead','Alex','Mead','0','armead@umich.edu'),
('cmuhich','Christopher','Muhich','111','cmuhich@gmail.com'),
('khpatel','Karan','Patel','122','khpatel@umich.edu'),
('kjschill','Kristopher','Schilling','125','kjschill@umich.edu'),
('kphall','Karen','Hall','124','kphall@umich.edu'),
('ppoisson','Phillip','Poisson','123','ppoisson@umich.edu'),
('rabani','Rosa','Abani','88','rabani@umich.edu'),
('britflah','Brittany','Flaherty','130','britflah@umich.edu'),
('chelseae','Chelsea','Ellis','126','chelseae@umich.edu'),
('cwyckoff','Casady','Wyckoff','128','cwyckoff@umich.edu'),
('adcunha','Asha','D\'Cunha','176','adcunha@umich.edu'),
('genevich','David','Genevich','131','genevich@umich.edu'),
('smpraus','Stephanie','Praus','127','smpraus@umich.edu'),
('tabuesch','Todd','Bueschen','129','tabuesch@umich.edu'),
('rgappel','Robert','Appel','155','rgappel@gmail.com'),
('jrilly','Jessica','Rilly','135','jrilly@umich.edu'),
('jwfong','Jessica','Fong','134','jwfong@umich.edu'),
('sbatch','Steven','Batchelor','136','sbatch@umich.edu'),
('marcmarc','Marcus','Lewis','137','marcmarc@umich.edu'),
('rmeggert','Rachel','Eggert','139','rmeggert@umich.edu'),
('ryakee','Ryan','McKee','140','ryanmckee87@gmail.com'),
('audosbo','Audra','Osborne','138','audosbo@umich.edu'),
('rbiswas','Rohan','Biswas','151','rbiswas@umich.edu'),
('eaboett','Liz','Boettner','148','eaboett@umich.edu'),
('changmar','Margaret','Chang','144','changmar@umich.edu'),
('nclay','Nicholas','Clay','145','nclay@umich.edu'),
('dallj','Jeremy','Dall','150','dallj@umich.edu'),
('ryaneth','Ryan','Ethier','147','ryaneth@umich.edu'),
('vward@umich.edu','Veronica','Ward','154','vward@umich.edu'),
('samcdev','Shannon','McDevitt','153','samcdev@umich.edu'),
('rapete','Rachel','Peterson','141','rapete@umich.edu'),
('rosephi','Philip','Rose','146','rosephi@umich.edu'),
('ishaanjs','Ishaan','Shah','152','ishaanjs@umich.edu'),
('siukathr','Kathryn','Siuniak','149','siukathr@umich.edu'),
('jmvan','Jillian','VandePutte','143','jmvan@umich.edu'),
('hwangm','Maggie','Hwang','142','hwangm@umich.edu'),
('aavila','Aaron','Avila','170','aavila@umich.edu'),
('jgfernan','Jason','Fernandez','159','jgfernan@umich.edu'),
('bethgles','Bethany','Glesner','161','bethanyg27@gmail.com'),
('megjoki','Meghan','Joki','164','megjoki@gmail.com'),
('maxkotu','Max','Kotula','167','maxkotu@umich.edu'),
('waimanl','Waiman','Liu','166','waimanl@umich.edu'),
('kunalm','Kunal','Mehta','163','kunalm@umich.edu'),
('catpat','Catherine','Patterson','162','catpat@umich.edu'),
('lapohl','Lyndsey','Pohl','165','lapohl@umich.edu'),
('ccschul','Caitlin','Schultz','160','ccschul@umich.edu'),
('emstark','Ethan','Stark','168','emstark@umich.edu'),
('mikeqin','Michael','Qin','169','mikeqin@umich.edu'),
('andybrwn','Andy','Brown','173','andybrwn@umich.edu'),
('carteraj','A.J.','Carter','177','carteraj@umich.edu'),
('dmcewan','Doug','McEwan','182','dmcewan@umich.edu'),
('hdorer','Heather','Dorer','175','hdorer@umich.edu'),
('jtmi','Josh','Miyamoto','179','jtmi@umich.edu'),
('lcrook','Laura','Crookston','178','lcrook@umich.edu'),
('mwinsemi','Mary','Winsemius','172','mwinsemi@umich.edu'),
('aagrajek','Abby','Grajek','189','aagrajek@umich.edu'),
('aarthara','Aarthi','Arab','188','aarthara@umich.edu'),
('aosorio','Antonio','Osorio','191','aosorio@umich.edu'),
('flynnmo','Molly','Flynn','187','flynnmo@umich.edu'),
('jbrendel','Jason','Brendel','185','jbrendel87@gmail.com'),
('jrswift','James','Swift','190','jrswift@umich.edu'),
('njmontes','Nicholas','Montes','184','njmontes@umich.edu'),
('nklam','Nathan','Klamerus','186','nklamerus@gmail.com'),
('tindeck','Thomas','Indeck','183','tindeck@umich.edu'),
('mhensel','Marc','Hensel','248','mhensel@umich.edu'),
('kriskim','Kristina','Kim','247','kriskim@umich.edu'),
('caitlincramer12','Caitlin','Cramer','196','ccram@umich.edu'),
('cmillera','Cameron','Miller','195','cmillera@umich.edu'),
('esoybay','Eda','Soybay','200','esoybay@umich.edu'),
('gmcewan','Greg','McEwan','201','gmcewan@umich.edu'),
('kamalk','Kamal','Knight','202','kamalk@umich.edu'),
('kfairc','Kyle','Faircloth','194','kfairc@umich.edu'),
('mfaibish','Melanie','Faibish','197','mfaibish@umich.edu'),
('michfern','Michelle','Fernandes','198','michfern@umich.edu'),
('malvikab','Malvika','Bhatia','199','malvikab@umich.edu'),
('ajinebge','George','Ajine-Basil','208','ajinebge@umich.edu'),
('asenyk','Abigail','Senyk','192','asenyk@umich.edu'),
('coolbre','Breanna','Luckett','203','coolbre@umich.edu'),
('csaucier','Celine','Saucier','217','csaucier@umich.edu'),
('gbhatia','Geetika','Bhatia','214','gbhatia@umich.edu'),
('harrisri','Rianna','Harris','210','harrisri@umich.edu'),
('jmartog','Joseph','Martoglio','212','jmartog@umich.edu'),
('alexng','Alexander','Ng','218','alexng@umich.edu'),
('ccprice','Carolyn','Price','221','ccprice@umich.edu'),
('cecamp','Charlotte','Campbell','219','cecamp@umich.edu'),
('maramae','Mara','Watson','204','maramae@umich.edu'),
('nabani','Nina','Abani','205','nabani@umich.edu'),
('nataaron','Nathaniel','Blase','207','nataaron@umich.edu'),
('ncozen','Naz','Ozen','215','ncozen@umich.edu'),
('rlakhani','Rahul','Lakhani','209','rlakhani@umich.edu'),
('rohansawalka','Rohan','Sawalka','216','rohansaw@umich.edu'),
('shdeitt','Scott','Deittrick','211','shdeitt@umich.edu'),
('simsbl','Brandon','Sims','213','simsbl@umich.edu'),
('thanav','Vivek','Thanabal','206','thanav@umich.edu'),
('domlanni','Dominic','Lanni','224','domlanni@umich.edu'),
('erekn','Erek','Walker','229','erekn@umich.edu'),
('kachou','Kathleen','Chou','220','kachou@umich.edu'),
('kelemley','Kristin','Lemley','225','kelemley@umich.edu'),
('kwolok','Kyle','Wolok','226','kwolok@umich.edu'),
('ldemonte','Elizabeth','DeMonte','222','ldemonte@umich.edu'),
('lispag','Lisandra','Pagan','223','lispag@umich.edu'),
('natbrwn','Natalie','Brown','228','natbrwn@umich.edu'),
('saraali','Sara','Ali','230','saraali@umich.edu'),
('stridas','Astrid','Santiago','227','stridas@umich.edu'),
('sylviach','Sylvia','Chen','231','siya101@gmail.com'),
('albanka','Alison','Banka','239','albanka@umich.edu'),
('zepeda','Yanet','Zepeda','241','zepeda@umich.edu'),
('clooney','Chrissy','Looney','242','clooney@umich.edu'),
('rkreiter','Ryan','Kreiter','238','rkreiter@umich.edu'),
('ryanbell','Ryan','Bell','232','ryanbell@umich.edu'),
('ehorste','Ellen','Horste','244','ehorste@umich.edu'),
('reozdowy','Richard','Ozdowy','234','reozdowy@umich.edu'),
('malinare','Rebecca','Malinas','245','malinare@umich.edu'),
('thumme','Mitchell','Thumme','236','thumme@umich.edu'),
('jyiyang','Jackie','Jo','240','jackiejiao3@gmail.com'),
('monticme','Meredith','Monticello','233','monticme@umich.edu'),
('justingk','Justin','Koehler','243','justingk@umich.edu'),
('jumilton','Julia','Zarina','235','jumilton@umich.edu'),
('duanmua','Alan','Duanmu','246','duanmua@umich.edu'),
('tanayn','Tanay','Nerurkar','249','tanayn@umich.edu'),
('meland','Matthew','Land','163.163 DG','meland@umich.edu'),
('aczubko','Allie','Czubko','254','aczubko@umich.edu'),
('alancast','Alexandros','Lancaster','259','alancast@umich.edu'),
('rovinski','Austin','Rovinski','251','rovinski@umich.edu'),
('christag','Christa','Gibara','255','christag@umich.edu'),
('dingding','Daoxia','Ding','262','dingding@umich.edu'),
('emjburns','Emily','Burns','256','emjburns@umich.edu'),
('jessewst','Jesse','Streicher','252','jessewst@umich.edu'),
('sungkj','Ki-Joo','Sung','250','sungkj@umich.edu'),
('kunaln','Kunal','Naik','261','kunaln@umich.edu'),
('lcpol','Lauren','Pollard','258','lcpol@umich.edu'),
('isaak','Nicholas','Simopoulos','260','isaak@umich.edu'),
('rhchoi','Robin','Choi','253','rhchoi@umich.edu'),
('rhsunnie','Ritong','Han','257','rhsunnie@umich.edu'),
('nkhm','Krishnan','Manivannan','276','nkhm@umich.edu'),
('ruansj','Sijie','Ruan','268','ruansj@umich.edu'),
('srishtip','Srishti','Pillutla','270','srishtip@umich.edu'),
('cascook','Cassandra','Cook','273','cascook@umich.edu'),
('minnaepc','Minnae','Chabwera','269','minnaepc@umich.edu'),
('louk','Kimberly','Louie','277','louk@umich.edu'),
('repatin','Ryan','Patin','266','repatin@umich.edu'),
('jaiyeong','Jai','Koh','281','jaiyeong@umich.edu'),
('cawleyc','Corryn','Cawley','280','cawleyc@umich.edu'),
('gabelok','Gabrielle','Belok','265','gabelok@umich.edu'),
('botatoes','Bo-ying','Fu','264','botatoes@umich.edu'),
('zmklav','Zachary','Klaver','272','zmklav@umich.edu'),
('jiaxin','Jiaxin','Wang','275','jiaxin@umich.edu'),
('mmangle','Marie','Angle','267','mmangle@umich.edu'),
('emichang','Emily','Chang','271','emichang@umich.edu'),
('ebklouda','Emily','Klouda','282','ebklouda@umich.edu'),
('gapoorva','Apoorva','Gupta','263','gapoorva@umich.edu'),
('sachinkj','Sachin','Jain','278','sachinkj@umich.edu'),
('bjuhrend','Brianna','Juhrend',' 262.21 LD','bjuhrend@umich.edu'),
('lowekiah','Kiah','Lowe','290','lowekiah@umich.edu'),
('jimsiang','Dan','Lee','279','jimsiang@umich.edu'),
('aoaoaoa','Andrew','Ao','287','aoaoaoa@umich.edu'),
('haohsu','Howard','Hsu','285','haohsu@umich.edu'),
('tkem','Tyler','Kemerer','283','tkem@umich.edu'),
('jasleung','Jason','Leung','284','jasleung@umich.edu'),
('yuanm','Molly','Ma','289','yuanm@umich.edu'),
('xiaobpan','Kristina','Pan','288','xiaobpan@umich.edu'),
('vidhyasr','Srividhya (Srivdi) ','Sridhar','286','vidhyasr@umich.edu'),
('andyjm','Andrew','McCaughna','298','andyjm@umich.edu'),
('chanmeec','Chanmee','Chung','303','chanmeec@umich.edu'),
('cmmcd','Christopher','McDonald','306','cmmcd@umich.edu'),
('cmbaums','Clarissa','Baumgarten','297','cmbaums@umich.edu'),
('dahodge','David','Hodgson','301','dahodge@umich.edu'),
('derino','Derin','Ozen','296','derino@umich.edu'),
('emiupton','Emily','Upton','0','emiupton@umich.edu'),
('damjohn','John','Damrath IV','294','damjohn@umich.edu'),
('jordandr','Jordan','Ridenour','293','jordandr@umich.edu'),
('jgussert','Joseph','Gussert','292','jgussert@umich.edu'),
('kevinjou','Kevin','Jou','0','kevinjou@umich.edu'),
('nxlouie','Nathan','Louie','304','nxlouie@umich.edu'),
('nricci','Nicholas','Ricci','0','nricci@umich.edu'),
('patwan','Patrick','Wan','299','patwan@umich.edu'),
('ralevens','Rachel','Levenson','302','ralevens@umich.edu'),
('sjdo','Steven','Do','300','sjdo@umich.edu'),
('trburch','Travis','Burch','291','trburch@umich.edu'),
('venugovi','Vikas','Venugopal','305','venugovi@umich.edu'),
('kimyusun','Yusun','Kim','295','kimyusun@umich.edu'),
('zlask','Zachary','Lask','0','zlask@umich.edu'),
('jeremylc','Jeremy','Chen','0','jeremylc@umich.edu'),
('jgaulzet','Jamie','Gaulzetti','0','jgaulzet@umich.edu'),
('lizsgoul','Liz','Goulston','0','lizsgoul@umich.edu'),
('willhorn','Will','Horner','0','willhorn@umich.edu'),
('jennyhuh@umich.edu','Jenny','Huh','0','jennyhuh@umich.edu'),
('ckokenoz','Cigdem ','Kokenoz','0','ckokenoz@umich.edu'),
('lhmarks','Lucas','Marks','0','lhmarks@umich.edu'),
('jmolesky','Jared','Molesky','0','jmolesky@umich.edu'),
('fpenikis','Francine','Penikis','0','fpenikis@umich.edu'),
('sanjsub','Sanjay','Subramanian','0','sanjsub@umich.edu'),
('atammana','Aditya','Tammana','0','atammana@umich.edu'),
('mwald','Matthew','Waldman','0','mwald@umich.edu'),
('troywe','Troyer','Wallace-Evans','0','troywe@umich.edu');

INSERT INTO profile (userid, major, city, state, pledge_class, nickname, phone, biguserid) VALUES 
('mjquinn','Electrical Engineering','','','Iota','','','kgunberg'),
('reedml','Civil Engineering','Royal Oak','MI','Lambda','S&M','734-330-9551','rmsherm'),
('kgunberg','Civil Engineering','Blacksburg','VA','Theta','Chalky','616-450-3405','jrtervol'),
('pconlin','Psychology','','','Eta','Gilligan','734-474-3700','rbronson'),
('gregfi','Nuclear Engineering','Pittsburgh','PA','Iota','Mini-Carl','412-721-6465','pdoll'),
('patelmn','Aerospace Engineering','','','Iota','JB','774-254-3794','jjwashbu'),
('jfairchi','Computer Engineering','Chicago','IL','Iota','The Flash','312-608-5655','jrtervol'),
('darrint','Computer Science Engineering','Chicago','IL','Zeta','Rain Man','312-576-9406','philipw'),
('dbzero','Computer Engineering','Superior Twp','MI','Founders','Nacho','248-219-6127','0'),
('ensignlm','Mechanical Engineering','','','Kappa','Bubbles','','angraor'),
('rauchs','Industrial and Operations Engineering','','','Eta','Duct Tape','734-812-0694','rileym'),
('squintan','Aerospace Engineering','Albuquerque','NM','Eta','Snowball','702-426-7797','rbronson'),
('jjwashbu','Computer Science Engineering','','','Eta','That Guy','734-306-1006','darrint'),
('quanz','Chemical Engineering','','','Lambda','','','darrint'),
('rburkhar','Aerospace Engineering','','','Eta','Corndogg','','darrint'),
('kdashair','','','','Iota','Dawg','734-837-5696','mgiska'),
('pdoll','Mechanical Engineering','','','Theta','','734-644-2985','rbronson'),
('angraor','AOSS','','','Iota','Princess Commando','734-730-0760','emr'),
('jlkron','Industrial and Operations Engineering','','','Iota','Yippy','313-570-5334','bsw'),
('dpinkney','','','','Iota','','','rburkhar'),
('emschmid','Mechanical Engineering','','','Theta','','734-516-0113','jmellent'),
('jcgrimm','Mechanical Engineering','','','Iota','WorstOTever','734-646-6343','bkilbour'),
('malbrigh','Mechanical Engineering','San Luis Obispo','CA','Iota','Righto','734-748-0084','jmellent'),
('stoloreb','Mechanical Engineering','','','Iota','Lefty','732-236-4756','emschmid'),
('davemich','Chemical Engineering and Materials Science','','','Iota','Big Dave','248-790-9454','rileym'),
('akluck','Computer Science Engineering','Centreville','VA','Iota','D.P.','517-304-1270','rauchs'),
('markalan','Aerospace Engineering','Chicago','IL','Iota','P.O.O.','','jdaunoravicius'),
('kofahlum','Industrial Operations Engineering','Brighton','MI','Iota','Divine Wind','734-272-2335','darrint'),
('rmsherm','Aerospace Engineering','Palmdale','CA','Iota','Fry','734-891-7922','lravindr'),
('alexkotu','Industrial and Operations Engineering','','','Kappa','Pinch \'N\' Run','612-868-3109','jdaunoravicius'),
('mjbyom','Computer Engineering','Campbell','CA','Kappa','The Magic Dragon','408-410-7691','jjwashbu'),
('mmbowman','Biomedical Engineering','','','Kappa','Byom','517-449-8329','jmellent'),
('schremsa','Computer Engineering','','','Kappa','Holidae In','','pconlin'),
('sbarr','Aerospace Engineering','','','Kappa','','734-945-8453','kdashair'),
('jmdonogh','Electrical Engineering','','','Kappa','','269-369-5493','kgunberg'),
('dparrotb','Mechanical Engineering','East Lansing','MI','Kappa','Caulk Mobster','','rauchs'),
('maherk','','','','Kappa','','','bsw'),
('andredan','IOE','','','Rho','','616-250-7061','schremsa'),
('tketai','Mechanical Engineering','','','Zeta','Smooth','734-355-5688','jhschaef'),
('milliken','Industrial and Operations Engineering','','','Lambda','','269-876-9502','tketai'),
('katsb','Aerospace','','','Lambda','Envy','561-601-5370','angraor'),
('emr','Mechanical Engineering','','','Eta','Skipper','517-896-3136','dbzero'),
('cmarti','Material Science and Engineering','Ann Arbor','MI','Mu','Mom','810-287-1823','rauchs'),
('benfried','Aerospace Engineering','Seattle','WA','Mu','Clogger','734-358-7086','jfairchi'),
('muskr','Electrical Engineering','Beavercreek','OH','Founders','Lizard','937-212-1182','0'),
('cworthem','Mechanical Engineering','Canton','MI','Founders','Random','734-276-6783','0'),
('jbroggio','','','','Founders','Ponch','','0'),
('rsekela1','','','','Founders','Monkey','','0'),
('derekdcs','Industrial and Operations Engineering','','','Founders','Derek','','0'),
('rmeder','','','','Founders','Mr. Clean','','0'),
('jjbailey08','Industrial and Operations Engineering','Oxford','MI','Founders','Chia','248-707-9028','0'),
('afurman','','','','Alpha','Goo','','rmeder'),
('mfeustel','Mechanical Engineering','','','Alpha','Butterknife Pete','734-417-8116','jjbailey08'),
('batchac','Electrical Engineering','','','Alpha','Spark','817-874-5951','dbzero'),
('mascione','Computer Engineering / MBA-MEM','','','Alpha','Fozzie','734-904-0007','jbroggio'),
('aolosfsk','','','','Alpha','Shady','734-516-9491','derekdcs'),
('jhschaef','Material Science and Engineering','Fort Wayne','IN','Alpha','Bean','260-494-5998','jjbailey08'),
('david.moenssen','','','','Alpha','Supa Dave','','muskr'),
('todd_moilanen','','','','Alpha','Tad','','muskr'),
('dcepeda','','','','Alpha','Mad Dogg','','jbroggio'),
('sbisgaie','Computer Engineering','','','Alpha','Biscuit','','cworthem'),
('qzhxfp','Industrial Operations Engineering','','','Beta','Weezie','810-210-2486','dbzero'),
('jpmyers','Mechanical Engineering','','','Beta','J.P. / Too Tall','734-223-9365','david.moenssen'),
('dwallen','Mechanical Engineering','','','Beta','Crispy','517-599-3359','jhschaef'),
('philipw','','','','Beta','Goose','','mascione'),
('molsofsk','Chemical Engineering','','','Beta','Lil\' O','734-834-6564','jbroggio'),
('gsabo','','','','Beta','Staples','','dcepeda'),
('mehtat','Chemical Engineering','','','Beta','T-Bone','','aolosfsk'),
('mgiska','Mechanical Engineering','Troy','MI','Gamma','Mother','734-751-9203','philipw'),
('stepania','EE: Systems','','','Gamma','','734-223-0861','qzhxfp'),
('avalique','','','','Gamma','','','jjbailey08'),
('ntapia','Electrical Engineering','','','Gamma','Nit','734-883-1141','mascione'),
('jjinnah','EECS','','','Delta','','571-643-4689','philipw'),
('jdaunoravicius','Computer Engineering','','','Epsilon','','708-359-6335','avalique'),
('lravindr','Computer Engineering','Marlboro','NJ','Zeta','Scandalous','','batchac'),
('jrtervol','IOE','','','Zeta','','804-314-9012','sbisgaie'),
('cvanitt','','','','Zeta','','','mehtat'),
('mperaino','','','','Zeta','','','qzhxfp'),
('bkilbour','','','','Eta','','','dwallen'),
('jmellent','Aerospace & Mechanical Engineering','Phoenixville','PA','Gamma','','','jhschaef'),
('rileym','Mechanical Engineering','','','Delta','Bob / Mack','734-678-4816','qzhxfp'),
('rbronson','Aerospace Engineering','','','Epsilon','B.J. Eunichre','','jjinnah'),
('bsw','Biomedical Engineering','','','Zeta','Shaft','','dwallen'),
('cdsadler','Chemical Engineering and MSE','','','Nu','','989-245-2656','malbrigh'),
('ebusen','Aerospace','Redondo Beach','CA','Nu','Magellan','424-903-9740','darrint'),
('fltr','Electrical Engineering','','','Xi','Floater','646-712-4080','schremsa'),
('meganelb','Nuclear Engineering & Radiological Sciences','','','Upsilon','','','rmeggert'),
('fszalay','Aerospace Engineering','Herndon','VA','Nu','Cyclone','571-314-1620','tketai'),
('furlongl','IOE','','','Nu','Dynamite','','angraor'),
('jamesbl','Mechanical','','','Nu','B.U.M.','734-476-7129','jfairchi'),
('jldolan','Nuclear Engineering','','','Nu','','517-648-2698','ensignlm'),
('jsuther','Mechanical Engineering','','','Nu','','248-703-2702','jcgrimm'),
('mezen','IOE','','','Nu','','440-823-9182','sbarr'),
('hnpatel','IOE','','','Xi','No Pants','734-507-5204','markalan'),
('kert','Electrical Engineering','','','Xi','','812-249-5728','rauchs'),
('hkast','Chemical Engineering/Pre-Med','','MI','Xi','','','kgunberg'),
('jamesrg','Materials Science and Engineering','Lake Angelus','MI','Epsilon Beta','','248-421-5159','ajinebge'),
('mwrod','Electrical Engineering','','','Nu','Father Rod','734-837-9370','kdashair'),
('nkizy','Computer Engineering','West Bloomfield','MI','Nu','Beads','248-496-1854','jlkron'),
('sassyk','MSE','','','Nu','','248-202-2927','rauchs'),
('smiatrow','Aerospace Engineering','','','Nu','','734-649-9559','kgunberg'),
('kjsand','Materials Science and Engineering','','','Xi','','989-430-8970','emr'),
('xjsixjag','Linguistics, Chinese Language and Culture','New York','NY','Nu','','989-450-0367','schremsa'),
('freemaja','IOE','Northville','','Omicron','','','alexkotu'),
('ajfrantz','Computer Engineering','','','Omicron','Supple','313-231-1906','mjbyom'),
('clemense','Mechanical Engineering','','','Omicron','Pinball','248-302-4398','rmsherm'),
('jengehle','Chemical Engineering','','','Omicron','D\'Over','517-294-6604','dparrotb'),
('mirim','Biomedical Engineering','Ann Arbor','MI','Omicron','','512-796-4810','jldolan'),
('weitung','Mechanical Engineering','','','Omicron','Money Shot','','cdsadler'),
('grailo','Aerospace','','','Omicron','Peaches','319-899-3760','rabani'),
('vinnyv','IOE','','','Omicron','F.T.','516-398-2059','reedml'),
('stanvi','Biomedical Engineering','Rochester Hills','MI','Omicron','','248-982-5938','jamesbl'),
('phalexan','Civil Engineering','Chesapeake','VA','Omicron','Tiger','919-308-4689','ebusen'),
('kadann','Chemical Engineering','','','Upsilon','','513-240-2198','cmarti'),
('armead','Civil Engineering','Grand Rapids','MI','Upsilon','M.J.','616-901-2479','vinnyv'),
('cmuhich','Chemical Engineering','Grosse Pointe Park','MI','Omicron','Cheese','313-806-6595','quanz'),
('khpatel','Aerospace Engineering, Space Systems Engineering','Bloomfield Hills','MI','Pi','Swiss Miss','248-613-5309','fszalay'),
('kjschill','Mechanical Engineering','','','Pi','','517-740-7835','schremsa'),
('kphall','Mechanical Engineering / Spanish','Reston','VA','Pi','','571-314-1626','ensignlm'),
('ppoisson','Mechanical Engineering','','','Pi','','248-770-4958','alexkotu'),
('rabani','Mechanical Engineering','Ann Arbor','MI','Mu','Too Big','734-717-6292','jlkron'),
('britflah','Chemical Engineering','','','Rho','','412-576-5661','cdsadler'),
('chelseae','Chemical Engineering','','','Rho','BFF','','cmarti'),
('cwyckoff','Materials Science & Engineering','Ferndale','MI','Rho','','517-316-5821','nkizy'),
('adcunha','Mechanical Engineering','Monroe','MI','Chi','','734-731-7698','smpraus'),
('genevich','Nuclear Engineering and Radiological Sciences','Southfield','MI','Rho','Road Runner','248-404-8479','mirim'),
('smpraus','AOSS','','','Rho','Scruffy','716-698-3307','jldolan'),
('tabuesch','Mechanical Engineering','Skillman','NJ','Rho','Mango','609-213-5164','cmuhich'),
('rgappel','Chemical Engineering','Beaumont','TX','Upsilon','Scooby Doo','248-933-0971','xjsixjag'),
('jrilly','Chemical Engineering','','','Sigma','Panch','248-835-6152','reedml'),
('jwfong','IOE','','','Sigma','Sniper','225-588-2825','jldolan'),
('sbatch','Mechanical Engineering','','','Sigma','','','jcgrimm'),
('marcmarc','Computer Science','','','Sigma','Crackerus Maximus','517-414-6049','akluck'),
('rmeggert','Nuclear Engineering and Radiological Sciences','Royal Oak','MI','Sigma','The Admiral','248-376-7020','kphall'),
('ryakee','Chemical Engineering','Philadelphia','PA','Sigma','Pool Boy','586-863-6693','ebusen'),
('audosbo','Aerospace Engineering','','','Sigma','RBT','734-735-1613','cmarti'),
('rbiswas','','','','Tau','','','khpatel'),
('eaboett','Mechanical Engineering','','','Tau','','845-661-1004','ppoisson'),
('changmar','Industrial and Operations Engineering','','','Tau','','','tabuesch'),
('nclay','Chemical Engineering','Dearborn','MI','Tau','RELAX','313-670-3036','vinnyv'),
('dallj','Aerospace Engineering','Grand Rapids','MI','Tau','','616-915-0676','ajfrantz'),
('ryaneth','Aerospace Engineering','Simsbury','CT','Tau','Heinie','860-817-8518','squintan'),
('vward@umich.edu','Industrial and Operations Engineering','Port Huron','MI','Upsilon','','','cwyckoff'),
('samcdev','Materials Science Engineering','Grosse Pointe Park','MI','Tau','','313-467-4358','genevich'),
('rapete','Biology','Hammond','IN','Tau','','219-742-2498','jrilly'),
('rosephi','Chemical Engineering','Battle Creek','MI','Tau','','269-274-7553','benfried'),
('ishaanjs','Business Administration - Finance','','','Tau','','734-846-4293','grailo'),
('siukathr','Chemical Engineering','Clarkston','MI','Tau','Nana','248-842-4399','jldolan'),
('jmvan','IOE','Clinton Twp.','MI','Tau','Handsy Flowerpot','586-610-2330','smiatrow'),
('hwangm','Nuclear Engineering and Radiological Sciences','Wilmington','NC','Tau','','248-840-6912','smpraus'),
('aavila','Chemical Engineering','St. Clair','MI','Phi','','810-434-4854','kphall'),
('jgfernan','Nuclear Engineering and Radiological Sciences','Ann Arbor','MI','Phi','Graaapedraaank 911','734-272-1964','ryaneth'),
('bethgles','Materials Science & Engineering','Milwaukee','WI','Phi','Leader','989-430-0349','jmvan'),
('megjoki','Materials Science and Engineering','Ann Arbor','MI','Phi','','248-935-1003','changmar'),
('maxkotu','Electrical Engineering','Eden Prairie','MN','Phi','AB Neg Potato Chip Candyp','952-334-7724','xjsixjag'),
('waimanl','Industrial and Operations Engineering','','','Phi','','269-830-6148','grailo'),
('kunalm','Biomedical Engineering','Novi','MI','Phi','The First Lady','248-345-8749','khpatel'),
('catpat','IOE','','','Phi','','','hwangm'),
('lapohl','Mechanical Engineering','Grand Ledge','MI','Phi','Hitch','517-204-9304','smpraus'),
('ccschul','Nuclear Engineering and Radiological Sciences','Leechburg','PA','Phi','Goldfish','724-355-9316','rmeggert'),
('emstark','Engineering Physics','Agoura Hills','CA','Phi','Wrecking Ball','818-274-8592','stanvi'),
('mikeqin','Industrial & Operations Engineering','','','Phi','2 Girls, 1 Football','617-584-1717','phalexan'),
('andybrwn','Civil and Environmental Engineering','Canton','MI','Chi','','734-812-9820','rbiswas'),
('carteraj','Electrical Engineering','Walled Lake','MI','Chi','Bingo','248-974-7037','siukathr'),
('dmcewan','Mechanical Engineering','','','Chi','Barcans','517-599-8575','rgappel'),
('hdorer','Mechanical Engineering','Chicago','IL','Chi','','810-623-9613','hwangm'),
('jtmi','Computer Engineering','Cheboygan','MI','Chi','','231-420-5215','cmuhich'),
('lcrook','Naval Architecture and Marine Engineering','Delton','MI','Chi','','269-370-0003','meganelb'),
('mwinsemi','Chemical Engineering','','','Chi','Tonya','231-903-7707','mirim'),
('aagrajek','Mechanical Engineering','Northville ','MI','Psi','','248-982-1494','genevich'),
('aarthara','Biomedical Engineering','Novi','MI','Psi','','248-345-7159','vward@umich.edu'),
('aosorio','Material Science and Engineering / Electrical Engineering','Pflugerville','TX','Psi','','512-431-5160','kadann'),
('flynnmo','Engineering Physics','Northville','MI','Psi','','678-548-4816','jgfernan'),
('jbrendel','Chemical Engineering','Ann Arbor','MI','Psi','','734-765-1675','rosephi'),
('jrswift','Biomedical Engineering','Albany','NY','Psi','','616-264-0123','andybrwn'),
('njmontes','Mechanical Engineering','','MI','Psi','','248-935-9206','mwinsemi'),
('nklam','Industrial and Operations Engineering','Drummond Island','MI','Psi','','906-748-1095','jrilly'),
('tindeck','Industrial and Operations Engineering','Palatine','IL','Psi','Pizza \'n Stuff','847-722-4572','siukathr'),
('mhensel','Mechanical Engineering','','','Zeta Beta','','','njmontes'),
('kriskim','Biomedical Engineering','','','Zeta Beta','','','kamalk'),
('caitlincramer12','Chemical Engineering','Troy','MI','Omega','','248-229-8615','megjoki'),
('cmillera','Nuclear Engineering and Radiological Sciences','Oakland Twp.','MI','Omega','','248-860-5734','siukathr'),
('esoybay','Industrial and Operations Engineering','','','Omega','','734-546-0632','bethgles'),
('gmcewan','Mechanical Engineering','','','Omega','AMURICAH!!','517-599-8320','siukathr'),
('kamalk','Electrical Engineering','Lanahm','MD','Omega','','301-704-8890','aavila'),
('kfairc','Applied Physics and Mechanical Engineering','Virginia Beach','VA','Omega','','','lcrook'),
('mfaibish','Industrial and Operations Engineering','','','Omega','','631-697-0625','hdorer'),
('michfern','Chemical Engineering','','','Omega','','248-974-5205','jmvan'),
('malvikab','Mechanical Engineering','','','Omega','','764-846-3771','ishaanjs'),
('ajinebge','Computer Engineering','Sterling Heights','MI','Gamma Beta','','586-808-0906','jtmi'),
('asenyk','Industrial and Operations Engineering','Grand Ledge','MI','Psi','Jaws','','bethgles'),
('coolbre','Industrial and Operations Engineering','Belleville','MI','Gamma Beta','','734-686-7746','mikeqin'),
('csaucier','Civil Engineering','Midland','MI','Gamma Beta','','989-941-1472','caitlincramer12'),
('gbhatia','Chemical Engineering','Mahalaxmi, Mumbai, India','','Gamma Beta','','734-926-7667','meganelb'),
('harrisri','Civil Engineering','Mt. Laurel','NJ','Gamma Beta','','856-246-2931','asenyk'),
('jmartog','Mechanical Engineering','Westfield','NJ','Gamma Beta','Poker Face','','tindeck'),
('alexng','Computer Science and Engineering','','','Delta Beta','','248-787-8851','waimanl'),
('ccprice','Computer Science ','','','Delta Beta','Jason Bourne','','michfern'),
('cecamp','Electrical Engineering and Theater Arts','Winnetka ','IL','Delta Beta','','847-212-8526','adcunha'),
('maramae','Nuclear Engineering and Radiological Sciences','Plainwell','MI','Gamma Beta','','269-290-8264','adcunha'),
('nabani','Materials Science and Engineering','Ann Arbor','MI','Gamma Beta','','734-330-9390','samcdev'),
('nataaron','Aerospace Engineering','waukesha','WI','Gamma Beta','Professor BroHo','262-993-7372','vward@umich.edu'),
('ncozen','Industrial and Operations Engineering','Istanbul/ TURKEY','','Gamma Beta','','734-730-9909','flynnmo'),
('rlakhani','Mechanical Engineering','Plano','TX','Gamma Beta','','','phalexan'),
('rohansawalka','Industrial and Operations Engineering','','','Gamma Beta','','734-565-3434','maxkotu'),
('shdeitt','Civil Engineering','Gobles','MI','Gamma Beta','','','dmcewan'),
('simsbl','Industrial and Operations Engineering','Rochester','MI','Gamma Beta','','248-672-2863','eaboett'),
('thanav','Mechanical Engineering','East Lyme','CT','Gamma Beta','MVP','860-941-9513','kunalm'),
('domlanni','Mechanical Engineering','','','Delta Beta','','248-935-3863','emstark'),
('erekn','Aerospace and Mechanical Engineering','','','Delta Beta','','','kfairc'),
('kachou','Materials Science and Engineering','Troy','MI','Delta Beta','','248-925-7880','mfaibish'),
('kelemley','Civil and Environmental Engineering','Caledonia','NY','Delta Beta','','585-409-1707','maxkotu'),
('kwolok','Biomedical Engineering','','','Delta Beta','','248-752-4343','cmillera'),
('ldemonte','Chemical Engineering','','','Delta Beta','','734-645-7493','esoybay'),
('lispag','Civil and Environmental Engineering','','','Delta Beta','Charmin','','nklam'),
('natbrwn','Mechanical Engineering','','','Delta Beta','','303-815-7598','nclay'),
('saraali','Industrial Operations Engineering','','','Delta Beta','','630-414-6257','carteraj'),
('stridas','Civil Engineering','Coral Gables','FL','Delta Beta','Astrid','','asenyk'),
('sylviach','Biomedical Engineering','Canton','MI','Delta Beta','','734-560-8797','ishaanjs'),
('albanka','Chemical Engineering','Muskegon','MI','Epsilon Beta','','231-670-7901','gbhatia'),
('zepeda','Civil Engineering','new rochelle','NY','Epsilon Beta','','','coolbre'),
('clooney','Mechanical Engineering','','','Epsilon Beta','','','michfern'),
('rkreiter','Computer Science and Engineering','','','Epsilon Beta','','586-222-9022','rohansawalka'),
('ryanbell','Biomedical Engineering','','','Epsilon Beta','','810-275-2106','cmillera'),
('ehorste','Biomedical Engineering','','','Epsilon Beta','','','aarthara'),
('reozdowy','Mechanical Engineering','','','Epsilon Beta','','','thanav'),
('malinare','Electrical Engineering','Northville','MI','Epsilon Beta','','248-912-7100','csaucier'),
('thumme','Computer Science','New Hudson','MI','Epsilon Beta','','989-980-8259','tindeck'),
('jyiyang','Civil Engineering','','','Epsilon Beta','','734-604-9125','ncozen'),
('monticme','Computer Science and Engineering','Northville','MI','Epsilon Beta','','248-880-1765','shdeitt'),
('justingk','Industrial and Operations Engineering','','','Epsilon Beta','','','alexng'),
('jumilton','','','','Epsilon Beta','','','esoybay'),
('duanmua','Computer Engineering','','','Zeta Beta','','','ccprice'),
('tanayn','Mechanical Engineering','','','Zeta Beta','Aquaman','703-409-0833','nataaron'),
('meland','M.S.E. Electrical Engineering','','','Transfer','','','0'),
('aczubko','Chemical Engineering','Ann Arbor','MI','Eta Beta','','734-474-0698','aagrajek'),
('alancast','Computer Science and Engineering','State College','PA','Eta Beta','xionmao (Panda)','814-933-9111','justingk'),
('rovinski','Electrical Engineering','Franklin','MI','Eta Beta','','248-914-2960','kwolok'),
('christag','Mechanical Engineering','Warren ','MI','Eta Beta','','586-601-6374','jumilton'),
('dingding','MS of Industrial and Operations Engineering','','','Eta Beta','','734-604-9869','ajinebge'),
('emjburns','Industrial and Operations Engineering','Ann Arbor','MI','Eta Beta','','734-945-2220','stridas'),
('jessewst','Mechanical Engineering','','','Eta Beta','Karate Kid','319-240-7612','duanmua'),
('sungkj','Chemical Engineering','','','Eta Beta','','231-903-7753','cecamp'),
('kunaln','Materials Science and Engineering','Marlboro','NJ','Eta Beta','','732-284-8546','ryanbell'),
('lcpol','','','','Eta Beta','','248-974-5480','clooney'),
('isaak','Chemical Engineering','Shelby Township','MI','Eta Beta','','','harrisri'),
('rhchoi','Mechanical Engineering','','','Eta Beta','FTK','','albanka'),
('rhsunnie','Industrial and Operations Engineering','South Lyon','MI','Eta Beta','Sunnie','','flynnmo'),
('nkhm','Computer Science and Engineering','','','Theta Beta','','','rohansawalka'),
('ruansj','Mechanical Engineering','','MI','Theta Beta','','734-834-8441','jessewst'),
('srishtip','Environmental Engineering','','','Theta Beta','','248-935-0307','rhsunnie'),
('cascook','','','','Theta Beta','','','malinare'),
('minnaepc','Aerospace Engineering','Newport News','VA','Theta Beta','','','kachou'),
('louk','undecided','','','Theta Beta','','','sungkj'),
('repatin','Engineering ','Canton','MI','Theta Beta','','734-377-8118','rhchoi'),
('jaiyeong','','','','Theta Beta','','','isaak'),
('cawleyc','','','','Theta Beta','','','ncozen'),
('gabelok','Chemical Engineering','Teaneck','NJ','Theta Beta','','','ldemonte'),
('botatoes','Computer Science and Engineering','','','Theta Beta','','702-326-5885','aczubko'),
('zmklav','Chemical Engineering','Laingsburg','MI','Theta Beta','','517-204-5183','domlanni'),
('jiaxin','','','','Theta Beta','','','tanayn'),
('mmangle','','','','Theta Beta','','650-218-4255','harrisri'),
('emichang','CS/BBA','Ann Arbor','MI','Theta Beta','','734-272-1314','christag'),
('ebklouda','Engineering','Westport','CT','Theta Beta','','','emjburns'),
('gapoorva','Computer Science Engineering','Rochester Hills','MI','Theta Beta','','248-860-6707','mhensel'),
('sachinkj','','','','Theta Beta','','','kunaln'),
('bjuhrend','MS Environmental Engineering ','','','Transfer','','530-391-5805','ajinebge'),
('lowekiah','Naval Architecture and Marine Engineering','Ypsilanti','MI','Theta Beta','Tickle Me Elmo','','rkreiter'),
('jimsiang','Chemical Engineering','','','Theta Beta','','248-318-2310','alexng'),
('aoaoaoa','Biomedical Engineering','Novi','MI','Iota Beta','','','rovinski'),
('haohsu','Chemical Engineering ','','','Iota Beta','','','rlakhani'),
('tkem','Mechanical Engineering/Pre-Dentistry','Freeland','MI','Iota Beta','','989-860-4047','zmklav'),
('jasleung','Computer Engineering','Novi','MI','Iota Beta','','248-921-0613','botatoes'),
('yuanm','','','','Iota Beta','','','gbhatia'),
('xiaobpan','','','','Iota Beta','','','monticme'),
('vidhyasr','','','','Iota Beta','','','christag'),
('andyjm','Aerospace Engineering','','','Kappa Beta','Cosby Sweaters','517-420-6269','sungkj'),
('chanmeec','IOE','','','Kappa Beta','Gollum Jenner','','kriskim'),
('cmmcd','Industrial and Operations Engineering','Bloomfield Hills','MI','Kappa Beta','Buzzcut','248-462-2067','botatoes'),
('cmbaums','','','','Kappa Beta','BM','','mmangle'),
('dahodge','Electrical Engineering','','','Kappa Beta','3D','','gabelok'),
('derino','','','','Kappa Beta','Piano Man','','monticme'),
('emiupton','','','','Kappa Beta','','','yuanm'),
('damjohn','','','','Kappa Beta','Megadeath','','mmangle'),
('jordandr','Computer Science and Engineering','','','Kappa Beta','Rally','','tkem'),
('jgussert','Mechanical Engineering','Cadillac','MI','Kappa Beta','A Log of Drums','231-942-2982','zmklav'),
('kevinjou','','','','Kappa Beta','','','aczubko'),
('nxlouie','','','','Kappa Beta','Sleepy Dwarf','','vidhyasr'),
('nricci','','','','Kappa Beta','','','repatin'),
('patwan','Computer Engineering','Ann Arbor','MI','Kappa Beta','Kung Fu Panda','734-846-7306','emichang'),
('ralevens','','','','Kappa Beta','The Porcelain Assassin','','ebklouda'),
('sjdo','','','','Kappa Beta','Mr. 300','','mwrod'),
('trburch','Mechanical Engineering','Champaign','IL','Kappa Beta','Blow Sober','217-390-6696','louk'),
('venugovi','Chemical Engineering','','','Kappa Beta','Jaeger Fairy','248-924-8188','jimsiang'),
('kimyusun','Chemical Engineering','','','Kappa Beta','BCC','201-655-1281','minnaepc'),
('zlask','','','','Kappa Beta','','','srishtip'),
('jeremylc','','','','Lambda Beta','','','gapoorva'),
('jgaulzet','','','','Lambda Beta','','','lcpol'),
('lizsgoul','','','','Lambda Beta','','','lowekiah'),
('willhorn','','','','Lambda Beta','','','derino'),
('jennyhuh@umich.edu','','','','Lambda Beta','','','louk'),
('ckokenoz','','','','Lambda Beta','','','cascook'),
('lhmarks','','','','Lambda Beta','','','jessewst'),
('jmolesky','Chemical Engineering','','','Lambda Beta','','','trburch'),
('fpenikis','','','','Lambda Beta','','','emichang'),
('sanjsub','Engineering','','','Lambda Beta','','732-610-4592','aoaoaoa'),
('atammana','','','','Lambda Beta','','','xiaobpan'),
('mwald','','','','Lambda Beta','','','jgussert'),
('troywe','Civil Engineering?','','','Lambda Beta','','847-644-7752','haohsu');

