<?php 
  /*
    SEARCHABLE TEMPLATE
      Takes:
        searchboxId: A string that uniquely identifies the seachbox component on the page
      Sends:
        A searchbox component that can search abitary corpuses.
      Returns:
        A array of dependency javascript file paths as strings (relative to the project root)
      Component Usage:
        A searchable object needs to be instantiated on the client-side JS. This object must then be linked with the HTML generated by this function through the searchboxId parameter given to this function.
  */

  function searchabletemplate($searchboxId) {
    $deps = array("js/searchable.js");
    
    // echo '<script type="text/javascript" src="'.$path_to_searchablejs.'"></script>';
?>
    <style type="text/css">
      .search {
        position: relative;
        margin-bottom: 30px;
        margin-top: 30px;
        z-index: 50;
      }
      .search input {
        height: 50px;
        font-size: 24px;
        border-radius: 0px;
        padding-right: 0;
      }
      .search.row > div {
        position: relative;
      }
      .search p {
        padding: 20px;
        font-weight: bold;
        margin: 0px; 
      }
      .search .suggestion-box {
        position: absolute;
        background-color: white;
        font-size 16px;
        top: 50px;
        display: none;
        padding: 0;
        width: calc(100% - 30px);
      }
      .search .suggestion {
        background-color: white;
        cursor: pointer;
      }
      .search .suggestion:hover {
        background-color: #003cb3;
        color: white;
      }

    </style>
    <div class="row search" id="<?php echo $searchboxId ?>">
      <div class="col-xs-12">
        <input type="text" class="form-control" placeholder="Search">
        <div class="suggestion-box"></div>
      </div>
    </div>
<?php
    return $deps;
  }
?>