<?php 
  /*
    SEARCHABLE TEMPLATE
      Takes:
        searchboxId: A string that uniquely identifies the seachbox component on the page
      Sends:
        A searchbox component that can search abitary corpuses.
      Returns:
        A array of dependency javascript file paths as strings (relative to the project root)
      Component Usage:
        A searchable object needs to be instantiated on the client-side JS. This object must then be linked with the HTML generated by this function through the searchboxId parameter given to this function.
  */

  function searchabletemplate($searchboxId) {
    $deps = array("js/searchable.js");
    
    // echo '<script type="text/javascript" src="'.$path_to_searchablejs.'"></script>';
?>
    <div class="row search" id="<?php echo $searchboxId ?>">
      <div class="col-xs-12">
        <input type="text" class="form-control" placeholder="Search">
        <div class="suggestion-box"></div>
      </div>
    </div>
<?php
    return $deps;
  }
?>